### ISSUE TITLE
How would you talk a horse-sized duck down from wanting to fight with you?

### ISSUE THREAD

**Issue by assertchris** [hafriedlander/ama#2]
Because violence against animals isn't cool...

**Comment by hafriedlander** [comment]
Unless horse-sized ducks have developed the ability to understand English (or, in a pinch, Indonesian), I don't think it matters how you talk to it. Try and look as little like bread as possible? Give it a fright and hope it's cardiovascular system hasn't coped with the scaling issues very well? Explain that we've evolved and/or been grown in a lab to take up very different evolutionary niches, and there's really no resource contention or other reason to fight?
