### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [hafriedlander/ama#4]

**Comment by hafriedlander** [comment]
My father brought home a Commodore Vic 20 when I was about 6. I don't have a lot of memory from that time, so this could be apocryphal, but there wasn't a lot of software available for purchase at the time - but there were a lot of magazines with programs in the back. So I'd type those in (a child has nothing in abundance as much as free time to waste) and then just started mucking about, changing them to do what I wanted.

I think resource limitation was a big driver of further exploration. Most creative hobbies have a cost of materials, but not programming - both the Vic 20 and the Commodore 64 had a basic interpreter right there as soon as you turned the machine on, and there was no cost to making a mistake, or just trying something for fun. On the other hand, I only started really getting into digital electronics once I was working and earning enough to afford a bunch of components (so I had one spare in case I let the smoke out accidentally).
