### ISSUE TITLE
What is the smallest change with the biggest impact to make the CMS faster?

### ISSUE THREAD

**Issue by unclecheese** [hafriedlander/ama#7]
Bonus points if you include the commit message of the patch.

**Comment by hafriedlander** [comment]
Unfortunately we've basically plucked all the low hanging fruit. Everything else that looks like low hanging fruit ends up being load-bearing in some irritating way.

I think the bootstrapping speed still needs a lot of work - even a NOP request takes 50ms or so, which makes lots-of-small-requests slower than it needs to be. The PJAX stuff is also a bit hand-rolled and error prone, so people tend to avoid it.

But the slowest thing by a long way is just the speed of layout in the CMS. I'd _so_ love to be able to move to flexbox or something. I think it's probably stable enough a spec now we could look to move to it at some point.
